### ISSUE TITLE
A file with one URL on the first line causes sed barfing

### ISSUE THREAD

**Issue by chdiza** [vszakats/https-check#1]
Make a textfile of only one line with just a URL on it, e.g., `http://github.com`.

The script then says:
```
sed: -e expression #1, char 2: invalid usage of line address 0
```

**Comment by vszakats** [comment]
On latest macOS I can't replicate this. What is your platform and sed flavour/version?

**Comment by chdiza** [comment]
macOS 10.12.6.
```
$ sed --version
sed (GNU sed) 4.4
```

**Comment by vszakats** [comment]
Thanks. This looks like GNU sed (`gnu-sed`) via Homebrew, installed with `--with-default-names` option. I could now replicate it.

GNU sed warns when referring to line zero while trying to look up the preceding line for a topmost one.  I'll fix this in the next commit.
